### ISSUE TITLE
overpayment in year 0?

### ISSUE THREAD

**Issue by weisjohn** [paulhoughton/mortgage#1]
First of all, this is awesome. Thanks so much for making this. 

There seems to be an issue in calculating overpayments in year 0. For example, let's say if I make a 10,000 payment in the first few months of the life of the loan:

![screen shot 2015-10-14 at 4 30 47 pm](https://cloud.githubusercontent.com/assets/12034/10496905/f5df68c8-7290-11e5-8798-85f99936209b.png)

**Comment by paulhoughton** [comment]
Payments start from year 1, current design is confusing because the table shows balance the end of the year but it's plotted at the start of the year on the chart.

Will look to revise.

**Comment by weisjohn** [comment]
@paulhoughton thanks for the info. That makes sense.

**Comment by paulhoughton** [comment]
Changed overpayments to years/months which makes this much clearer.

**Comment by weisjohn** [comment]
@paulhoughton I really appreciate that. Thanks for making this change! This is such an awesome tool!
